### ISSUE TITLE
Cannot set time or date

### ISSUE THREAD

**Issue by avengerdba** [AsteroidOS/meta-bass-hybris#6]
I tried rebooting, setting time and date from the device manually, using AsteroidOS Sync, but nothing worked
Version: AsteroidOS snaphsot-20190805

**Comment by FlorentRevest** [comment]
Could you try sshing into your watch as root and run "opkg configure" ? Then reboot the watch and let me know if you can set the time.
If you can, then this bug should be fixed in the next snapshot (built in a week from now)

**Comment by avengerdba** [comment]
It worked. The watch updated time and date from AsteroidOS Sync automatically
Thanks a lot!
