### ISSUE TITLE
Bluetooth not working

### ISSUE THREAD

**Issue by mbistricic** [AsteroidOS/meta-bass-hybris#8]
I have bought this watch primarily to connect it with my ubuntu touch phone using Telescope and to help with the development of this app. 
After installing AsteroidOS my watch does not get detected when scanning for bluetooth devices. Previously when android wear was installed the watch was detected by the android phone and it worked well.
I have (unsuccessfully) tried to detect my watch with the following devices:
- nexus 5 (hammerhead) which is on ubports ubuntu 16.04 OTA-11
- pc laptop on fedora 31
- pc laptop on windows
- android phone

I have AsteroidOS 1.1-nightly (https://release.asteroidos.org/nightlies/bass 2020-01-06) installed on my watch.
Please let me know if you need any more information.

**Comment by FlorentRevest** [comment]
Could you paste the output of the following commands run as root on the watch:
* hciconfig
* rfkill list 
* journalctl -u patchram.service

**Comment by mbistricic** [comment]
I would really like to do that, but my watch cannot be recognised even with usb connection. I have tried with adb (no devices or emulators detected) and with ssh (with address 192.168.2.15) - windows and linux. When I connect the watch to windows I got the following popup message:  "The last USB device you connected to this computer malfunctioned and Windows does not recognise it."
Can you provide me (linux/windows) instructions to properly connect my watch via usb?

**Comment by mbistricic** [comment]
I did succeed to connect to my watch using ssh on linux, but adb devices still does not detect it.
Nevertheless, here are the outputs:

root@bass:ceres# hciconfig
hci0:   Type: Primary  Bus: UART
        BD Address: 43:43:A0:12:1F:AC  ACL MTU: 1021:8  SCO MTU: 64:1
        UP RUNNING 
        RX bytes:1413 acl:0 sco:0 events:81 errors:0
        TX bytes:1591 acl:0 sco:0 commands:81 errors:0

root@bass:ceres# rfkill list
0: brcm_Bluetooth_rfkill: Bluetooth
        Soft blocked: no
        Hard blocked: no
1: phy0: Wireless LAN
        Soft blocked: yes
        Hard blocked: no
2: brcmfmac-wifi: Wireless LAN
        Soft blocked: yes
        Hard blocked: no
3: hci0: Bluetooth
        Soft blocked: no
        Hard blocked: no

root@bass:ceres# journalctl -u patchram.service
-- Logs begin at Sat 2020-01-25 07:32:48 UTC, end at Sat 2020-01-25 08:13:20 UTC. --
Jan 25 07:32:53 bass systemd[1]: Starting Load firmware into BCM4343A0 bluetooth chip...
Jan 25 07:32:53 bass systemd[1]: Started Load firmware into BCM4343A0 bluetooth chip.
Jan 25 07:33:02 bass brcm_patchram_plus[311]: Done setting line discpline

**Comment by StefWe** [comment]
I installed nightly from today 23.03.2020 and can confirm that bluetooth is not working any more. The watch get not detected by any other device.

`root@bass:ceres# hciconfig
hci0:   Type: Primary  Bus: UART
        BD Address: 43:43:A0:12:1F:AC  ACL MTU: 1021:8  SCO MTU: 64:1
        UP RUNNING 
        RX bytes:710 acl:0 sco:0 events:41 errors:0
        TX bytes:845 acl:0 sco:0 commands:41 errors:0
`

`root@bass:ceres# rfkill list
0: brcm_Bluetooth_rfkill: Bluetooth
        Soft blocked: no
        Hard blocked: no
1: phy0: Wireless LAN
        Soft blocked: yes
        Hard blocked: no
2: brcmfmac-wifi: Wireless LAN
        Soft blocked: yes
        Hard blocked: no
3: hci0: Bluetooth
        Soft blocked: no
        Hard blocked: no`

`-- Logs begin at Mon 2020-02-24 02:01:09 UTC, end at Mon 2020-02-24 02:08:41 UTC. --
Feb 24 02:01:14 bass systemd[1]: Starting Load firmware into BCM4343A0 bluetooth chip...
Feb 24 02:01:14 bass systemd[1]: Started Load firmware into BCM4343A0 bluetooth chip.
Feb 24 02:01:22 bass brcm_patchram_plus[326]: Done setting line 
`

**Comment by MagneFire** [comment]
@StefWe: Did this issue only start to occur with the nightly of 23-03-2020 or also the versions before that?

Can you remove `--baudrate 3000000` from `/lib/systemd/system/patchram.service` and see if that solves the problem?

**Comment by StefWe** [comment]
My last installation was based on builds from July 2019. I try to fix an issue with a newer version of asteroid os, that's the reason why i installed a new version

I removed the parameter but the problem is still there.

**Comment by StefWe** [comment]
I flashed the [stable](https://release.asteroidos.org/1.0/bass/) version and bluetooth is working as expected.

**Comment by mTorp22** [comment]
I can confirm, flashing the stable version makes bluetooth work again.

**Comment by StefWe** [comment]
Thank you for confirmation @mTorp22 

Hopefully that can be fixed.

**Comment by FlorentRevest** [comment]
Could you try the new nightlies? https://release.asteroidos.org/nightlies/bass/

**Comment by mTorp22** [comment]
Hi Just flashed my LG bass with the nightly build and this seems to have solved the issue. 
Thanks

**Comment by StefWe** [comment]
As always too late for the party, but I can confirm that Bluetooth works with the nightly build

**Comment by mbistricic** [comment]
Thank you all for your effort.
Can you please update https://release.asteroidos.org/nightlies/ipk/bass/ with the new version so the watch can be updated with opkg update/upgrade?
